language: ruby
cache: bundler
sudo: required

env:
  - PGVERSION=9.5

env:
  global:
    - PGPORT=5433

rvm:
  - 2.3.0

before_install:
  - wget https://gist.github.com/petere/5893799/raw/apt.postgresql.org.sh
  - wget https://gist.github.com/petere/6023944/raw/pg-travis-test.sh
  - sudo sh ./apt.postgresql.org.sh

services:
  - redis-server

before_script:
  - cp config/database.yml.travis config/database.yml

script:
  - sudo apt-get update
  - 'bash ./pg-travis-test.sh'
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.5
  - 'bundle exec rake db:create'
  - 'bundle exec rake db:schema:load'
  - 'bundle exec rspec'

notifications:
  email:
    recipients:
      - sebastian.schkudlara@vizzuality.com
    on_failure: change
    on_success: never

addons:
  code_climate:
    repo_token: cfc8b18f46c795f26485c055758b5d8b2d8bcacad80f14a30a2fb0e59fdad187
