language: ruby
cache: bundler

rvm:
  - 2.3.0

before_install:
  - sudo /etc/init.d/postgresql stop
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get install postgresql-9.5
  - sudo /etc/init.d/postgresql restart

services:
  - redis-server

before_script:
  - cp config/database.yml.travis config/database.yml

script:
  - 'bundle exec rake db:create'
  - 'bundle exec rake db:schema:load'
  - 'bundle exec rspec'

notifications:
  email:
    recipients:
      - sebastian.schkudlara@vizzuality.com
    on_failure: change
    on_success: never

addons:
  code_climate:
    repo_token: cfc8b18f46c795f26485c055758b5d8b2d8bcacad80f14a30a2fb0e59fdad187
