language: ruby
cache: bundler
sudo: required

rvm:
  - 2.3.0

addons:
  apt:
    sources:
      - precise-pgdg-9.5
    packages:
      - postgresql-9.5
      - postgresql-contrib-9.5
  postgresql: 9.5

env:
  global:
    - PGPORT=5433
    - PGHOST=localhost

services:
  - redis-server

before_script:
  - cp config/database.yml.travis config/database.yml
  - sudo /etc/init.d/postgresql restart

script:
  - 'bundle exec rake db:create'
  - 'bundle exec rake db:schema:load'
  - 'bundle exec rspec'

notifications:
  email:
    recipients:
      - sebastian.schkudlara@vizzuality.com
    on_failure: change
    on_success: never

addons:
  code_climate:
    repo_token: cfc8b18f46c795f26485c055758b5d8b2d8bcacad80f14a30a2fb0e59fdad187
