web:
  build: .
  command: run
  ports:
    - "3000:3000"
  links:
    - postgres
  volumes:
    - .:/rw_dataset

postgres:
  image: postgres
  container_name: rw_database_dataset-postgres
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_DB=rw_dataset_development